sonar.projectKey=CloudFoundry_multiapps-controller
sonar.organization=cloudfoundry
sonar.projectName="MultiApps Controller Parent"


sonar.exclusions=\
    **/target/generated-sources/**,\
    **/target/generated-test-sources/**,\
    multiapps-controller-coverage/**

sonar.coverage.exclusions=\
    multiapps-controller-core-test/**,\
    multiapps-controller-persistence-test/**,\
    multiapps-controller-api/**/model/**,\
    **/target/generated-sources/**,\
    **/Immutable*.java,\
    **/DatabaseConfiguration.java,\
    **/FlowableConfiguration.java,\
    **/FlowableServicesConfiguration.java,\
    **/JmxConfiguration.java,\
    **/MicrometerConfiguration.java,\
    **/UAAClientConfiguration.java
