CREATE TRIGGER DELETE_FROM_SYSTEM_TABLE_LM_SL_PERSISTENCE_FILE AFTER UPDATE OR DELETE
  ON LM_SL_PERSISTENCE_FILE FOR EACH ROW EXECUTE PROCEDURE UNLINK_FILE_CONTENT();

CREATE TRIGGER DELETE_FROM_SYSTEM_TABLE_PROCESS_LOG AFTER UPDATE OR DELETE
  ON PROCESS_LOG FOR EACH ROW EXECUTE PROCEDURE UNLINK_FILE_CONTENT();
