DROP TRIGGER IF EXISTS DELETE_FROM_SYSTEM_TABLE_LM_SL_PERSISTANCE_FILE ON LM_SL_PERSISTENCE_FILE;
DROP TRIGGER IF EXISTS DELETE_FROM_SYSTEM_TABLE_LM_SL_PERSISTENCE_FILE ON LM_SL_PERSISTENCE_FILE;
DROP TRIGGER IF EXISTS DELETE_FROM_SYSTEM_TABLE_PROCESS_LOG ON PROCESS_LOG;

DROP FUNCTION IF EXISTS UNLINK_FILE_CONTENT();
