// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log.proto

package com.sap.cloud.lm.sl.cf.client.events;

public final class LogFactory {
  private LogFactory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:events.LogMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *&#47; Bytes of the log message. (Note that it is not required to be a single line.)
     * </pre>
     *
     * <code>required bytes message = 1;</code>
     */
    boolean hasMessage();
    /**
     * <pre>
     *&#47; Bytes of the log message. (Note that it is not required to be a single line.)
     * </pre>
     *
     * <code>required bytes message = 1;</code>
     */
    com.google.protobuf.ByteString getMessage();

    /**
     * <pre>
     *&#47; Type of the message (OUT or ERR).
     * </pre>
     *
     * <code>required .events.LogMessage.MessageType message_type = 2;</code>
     */
    boolean hasMessageType();
    /**
     * <pre>
     *&#47; Type of the message (OUT or ERR).
     * </pre>
     *
     * <code>required .events.LogMessage.MessageType message_type = 2;</code>
     */
        LogFactory.LogMessage.MessageType getMessageType();

    /**
     * <pre>
     *&#47; UNIX timestamp (in nanoseconds) when the log was written.
     * </pre>
     *
     * <code>required int64 timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <pre>
     *&#47; UNIX timestamp (in nanoseconds) when the log was written.
     * </pre>
     *
     * <code>required int64 timestamp = 3;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     *&#47; Application that emitted the message (or to which the application is related).
     * </pre>
     *
     * <code>optional string app_id = 4;</code>
     */
    boolean hasAppId();
    /**
     * <pre>
     *&#47; Application that emitted the message (or to which the application is related).
     * </pre>
     *
     * <code>optional string app_id = 4;</code>
     */
    java.lang.String getAppId();
    /**
     * <pre>
     *&#47; Application that emitted the message (or to which the application is related).
     * </pre>
     *
     * <code>optional string app_id = 4;</code>
     */
    com.google.protobuf.ByteString
        getAppIdBytes();

    /**
     * <pre>
     *&#47; Source of the message. For Cloud Foundry, this can be "APP", "RTR", "DEA", "STG", etc.
     * </pre>
     *
     * <code>optional string source_type = 5;</code>
     */
    boolean hasSourceType();
    /**
     * <pre>
     *&#47; Source of the message. For Cloud Foundry, this can be "APP", "RTR", "DEA", "STG", etc.
     * </pre>
     *
     * <code>optional string source_type = 5;</code>
     */
    java.lang.String getSourceType();
    /**
     * <pre>
     *&#47; Source of the message. For Cloud Foundry, this can be "APP", "RTR", "DEA", "STG", etc.
     * </pre>
     *
     * <code>optional string source_type = 5;</code>
     */
    com.google.protobuf.ByteString
        getSourceTypeBytes();

    /**
     * <pre>
     *&#47; Instance that emitted the message.
     * </pre>
     *
     * <code>optional string source_instance = 6;</code>
     */
    boolean hasSourceInstance();
    /**
     * <pre>
     *&#47; Instance that emitted the message.
     * </pre>
     *
     * <code>optional string source_instance = 6;</code>
     */
    java.lang.String getSourceInstance();
    /**
     * <pre>
     *&#47; Instance that emitted the message.
     * </pre>
     *
     * <code>optional string source_instance = 6;</code>
     */
    com.google.protobuf.ByteString
        getSourceInstanceBytes();
  }
  /**
   * <pre>
   *&#47; A LogMessage contains a "log line" and associated metadata.
   * </pre>
   *
   * Protobuf type {@code events.LogMessage}
   */
  public  static final class LogMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:events.LogMessage)
      LogMessageOrBuilder {
    // Use LogMessage.newBuilder() to construct.
    private LogMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogMessage() {
      message_ = com.google.protobuf.ByteString.EMPTY;
      messageType_ = 1;
      timestamp_ = 0L;
      appId_ = "";
      sourceType_ = "";
      sourceInstance_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              message_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                            LogFactory.LogMessage.MessageType value = LogFactory.LogMessage.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                messageType_ = rawValue;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              appId_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              sourceType_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              sourceInstance_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return LogFactory.internal_static_events_LogMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return LogFactory.internal_static_events_LogMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
                LogFactory.LogMessage.class, LogFactory.LogMessage.Builder.class);
    }

    /**
     * <pre>
     *&#47; MessageType stores the destination of the message (corresponding to STDOUT or STDERR).
     * </pre>
     *
     * Protobuf enum {@code events.LogMessage.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OUT = 1;</code>
       */
      OUT(1),
      /**
       * <code>ERR = 2;</code>
       */
      ERR(2),
      ;

      /**
       * <code>OUT = 1;</code>
       */
      public static final int OUT_VALUE = 1;
      /**
       * <code>ERR = 2;</code>
       */
      public static final int ERR_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      public static MessageType forNumber(int value) {
        switch (value) {
          case 1: return OUT;
          case 2: return ERR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
                return LogFactory.LogMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:events.LogMessage.MessageType)
    }

    private int bitField0_;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString message_;
    /**
     * <pre>
     *&#47; Bytes of the log message. (Note that it is not required to be a single line.)
     * </pre>
     *
     * <code>required bytes message = 1;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *&#47; Bytes of the log message. (Note that it is not required to be a single line.)
     * </pre>
     *
     * <code>required bytes message = 1;</code>
     */
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    public static final int MESSAGE_TYPE_FIELD_NUMBER = 2;
    private int messageType_;
    /**
     * <pre>
     *&#47; Type of the message (OUT or ERR).
     * </pre>
     *
     * <code>required .events.LogMessage.MessageType message_type = 2;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *&#47; Type of the message (OUT or ERR).
     * </pre>
     *
     * <code>required .events.LogMessage.MessageType message_type = 2;</code>
     */
        public LogFactory.LogMessage.MessageType getMessageType() {
            LogFactory.LogMessage.MessageType result = LogFactory.LogMessage.MessageType.valueOf(messageType_);
            return result == null ? LogFactory.LogMessage.MessageType.OUT : result;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <pre>
     *&#47; UNIX timestamp (in nanoseconds) when the log was written.
     * </pre>
     *
     * <code>required int64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *&#47; UNIX timestamp (in nanoseconds) when the log was written.
     * </pre>
     *
     * <code>required int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int APP_ID_FIELD_NUMBER = 4;
    private volatile java.lang.Object appId_;
    /**
     * <pre>
     *&#47; Application that emitted the message (or to which the application is related).
     * </pre>
     *
     * <code>optional string app_id = 4;</code>
     */
    public boolean hasAppId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *&#47; Application that emitted the message (or to which the application is related).
     * </pre>
     *
     * <code>optional string app_id = 4;</code>
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appId_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *&#47; Application that emitted the message (or to which the application is related).
     * </pre>
     *
     * <code>optional string app_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_TYPE_FIELD_NUMBER = 5;
    private volatile java.lang.Object sourceType_;
    /**
     * <pre>
     *&#47; Source of the message. For Cloud Foundry, this can be "APP", "RTR", "DEA", "STG", etc.
     * </pre>
     *
     * <code>optional string source_type = 5;</code>
     */
    public boolean hasSourceType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *&#47; Source of the message. For Cloud Foundry, this can be "APP", "RTR", "DEA", "STG", etc.
     * </pre>
     *
     * <code>optional string source_type = 5;</code>
     */
    public java.lang.String getSourceType() {
      java.lang.Object ref = sourceType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceType_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *&#47; Source of the message. For Cloud Foundry, this can be "APP", "RTR", "DEA", "STG", etc.
     * </pre>
     *
     * <code>optional string source_type = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSourceTypeBytes() {
      java.lang.Object ref = sourceType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_INSTANCE_FIELD_NUMBER = 6;
    private volatile java.lang.Object sourceInstance_;
    /**
     * <pre>
     *&#47; Instance that emitted the message.
     * </pre>
     *
     * <code>optional string source_instance = 6;</code>
     */
    public boolean hasSourceInstance() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     *&#47; Instance that emitted the message.
     * </pre>
     *
     * <code>optional string source_instance = 6;</code>
     */
    public java.lang.String getSourceInstance() {
      java.lang.Object ref = sourceInstance_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceInstance_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *&#47; Instance that emitted the message.
     * </pre>
     *
     * <code>optional string source_instance = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSourceInstanceBytes() {
      java.lang.Object ref = sourceInstance_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceInstance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, message_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, messageType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, appId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sourceType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, sourceInstance_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, message_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, messageType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, appId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sourceType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, sourceInstance_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
            if (!(obj instanceof LogFactory.LogMessage)) {
        return super.equals(obj);
      }
            LogFactory.LogMessage other = (LogFactory.LogMessage) obj;

      boolean result = true;
      result = result && (hasMessage() == other.hasMessage());
      if (hasMessage()) {
        result = result && getMessage()
            .equals(other.getMessage());
      }
      result = result && (hasMessageType() == other.hasMessageType());
      if (hasMessageType()) {
        result = result && messageType_ == other.messageType_;
      }
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && (hasAppId() == other.hasAppId());
      if (hasAppId()) {
        result = result && getAppId()
            .equals(other.getAppId());
      }
      result = result && (hasSourceType() == other.hasSourceType());
      if (hasSourceType()) {
        result = result && getSourceType()
            .equals(other.getSourceType());
      }
      result = result && (hasSourceInstance() == other.hasSourceInstance());
      if (hasSourceInstance()) {
        result = result && getSourceInstance()
            .equals(other.getSourceInstance());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      if (hasMessageType()) {
        hash = (37 * hash) + MESSAGE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + messageType_;
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasAppId()) {
        hash = (37 * hash) + APP_ID_FIELD_NUMBER;
        hash = (53 * hash) + getAppId().hashCode();
      }
      if (hasSourceType()) {
        hash = (37 * hash) + SOURCE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getSourceType().hashCode();
      }
      if (hasSourceInstance()) {
        hash = (37 * hash) + SOURCE_INSTANCE_FIELD_NUMBER;
        hash = (53 * hash) + getSourceInstance().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

        public static LogFactory.LogMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

        public static LogFactory.LogMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

        public static LogFactory.LogMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

        public static LogFactory.LogMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

        public static LogFactory.LogMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

        public static LogFactory.LogMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

        public static LogFactory.LogMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

        public static LogFactory.LogMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

        public static LogFactory.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

        public static LogFactory.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

        public static Builder newBuilder(LogFactory.LogMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *&#47; A LogMessage contains a "log line" and associated metadata.
     * </pre>
     *
     * Protobuf type {@code events.LogMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:events.LogMessage)
            LogFactory.LogMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
                return LogFactory.internal_static_events_LogMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
                return LogFactory.internal_static_events_LogMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    LogFactory.LogMessage.class, LogFactory.LogMessage.Builder.class);
      }

            // Construct using LogFactory.LogMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        message_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        appId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sourceType_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        sourceInstance_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
                return LogFactory.internal_static_events_LogMessage_descriptor;
      }

            public LogFactory.LogMessage getDefaultInstanceForType() {
                return LogFactory.LogMessage.getDefaultInstance();
      }

            public LogFactory.LogMessage build() {
                LogFactory.LogMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

            public LogFactory.LogMessage buildPartial() {
                LogFactory.LogMessage result = new LogFactory.LogMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.appId_ = appId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sourceType_ = sourceType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sourceInstance_ = sourceInstance_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof LogFactory.LogMessage) {
                    return mergeFrom((LogFactory.LogMessage) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

            public Builder mergeFrom(LogFactory.LogMessage other) {
                if (other == LogFactory.LogMessage.getDefaultInstance())
                    return this;
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasAppId()) {
          bitField0_ |= 0x00000008;
          appId_ = other.appId_;
          onChanged();
        }
        if (other.hasSourceType()) {
          bitField0_ |= 0x00000010;
          sourceType_ = other.sourceType_;
          onChanged();
        }
        if (other.hasSourceInstance()) {
          bitField0_ |= 0x00000020;
          sourceInstance_ = other.sourceInstance_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessage()) {
          return false;
        }
        if (!hasMessageType()) {
          return false;
        }
        if (!hasTimestamp()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
                LogFactory.LogMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (LogFactory.LogMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *&#47; Bytes of the log message. (Note that it is not required to be a single line.)
       * </pre>
       *
       * <code>required bytes message = 1;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *&#47; Bytes of the log message. (Note that it is not required to be a single line.)
       * </pre>
       *
       * <code>required bytes message = 1;</code>
       */
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      /**
       * <pre>
       *&#47; Bytes of the log message. (Note that it is not required to be a single line.)
       * </pre>
       *
       * <code>required bytes message = 1;</code>
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; Bytes of the log message. (Note that it is not required to be a single line.)
       * </pre>
       *
       * <code>required bytes message = 1;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }

      private int messageType_ = 1;
      /**
       * <pre>
       *&#47; Type of the message (OUT or ERR).
       * </pre>
       *
       * <code>required .events.LogMessage.MessageType message_type = 2;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *&#47; Type of the message (OUT or ERR).
       * </pre>
       *
       * <code>required .events.LogMessage.MessageType message_type = 2;</code>
       */
            public LogFactory.LogMessage.MessageType getMessageType() {
                LogFactory.LogMessage.MessageType result = LogFactory.LogMessage.MessageType.valueOf(messageType_);
                return result == null ? LogFactory.LogMessage.MessageType.OUT : result;
      }
      /**
       * <pre>
       *&#47; Type of the message (OUT or ERR).
       * </pre>
       *
       * <code>required .events.LogMessage.MessageType message_type = 2;</code>
       */
            public Builder setMessageType(LogFactory.LogMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; Type of the message (OUT or ERR).
       * </pre>
       *
       * <code>required .events.LogMessage.MessageType message_type = 2;</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageType_ = 1;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       *&#47; UNIX timestamp (in nanoseconds) when the log was written.
       * </pre>
       *
       * <code>required int64 timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *&#47; UNIX timestamp (in nanoseconds) when the log was written.
       * </pre>
       *
       * <code>required int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       *&#47; UNIX timestamp (in nanoseconds) when the log was written.
       * </pre>
       *
       * <code>required int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; UNIX timestamp (in nanoseconds) when the log was written.
       * </pre>
       *
       * <code>required int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object appId_ = "";
      /**
       * <pre>
       *&#47; Application that emitted the message (or to which the application is related).
       * </pre>
       *
       * <code>optional string app_id = 4;</code>
       */
      public boolean hasAppId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *&#47; Application that emitted the message (or to which the application is related).
       * </pre>
       *
       * <code>optional string app_id = 4;</code>
       */
      public java.lang.String getAppId() {
        java.lang.Object ref = appId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *&#47; Application that emitted the message (or to which the application is related).
       * </pre>
       *
       * <code>optional string app_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        java.lang.Object ref = appId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *&#47; Application that emitted the message (or to which the application is related).
       * </pre>
       *
       * <code>optional string app_id = 4;</code>
       */
      public Builder setAppId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; Application that emitted the message (or to which the application is related).
       * </pre>
       *
       * <code>optional string app_id = 4;</code>
       */
      public Builder clearAppId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        appId_ = getDefaultInstance().getAppId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; Application that emitted the message (or to which the application is related).
       * </pre>
       *
       * <code>optional string app_id = 4;</code>
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        appId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sourceType_ = "";
      /**
       * <pre>
       *&#47; Source of the message. For Cloud Foundry, this can be "APP", "RTR", "DEA", "STG", etc.
       * </pre>
       *
       * <code>optional string source_type = 5;</code>
       */
      public boolean hasSourceType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *&#47; Source of the message. For Cloud Foundry, this can be "APP", "RTR", "DEA", "STG", etc.
       * </pre>
       *
       * <code>optional string source_type = 5;</code>
       */
      public java.lang.String getSourceType() {
        java.lang.Object ref = sourceType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sourceType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *&#47; Source of the message. For Cloud Foundry, this can be "APP", "RTR", "DEA", "STG", etc.
       * </pre>
       *
       * <code>optional string source_type = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSourceTypeBytes() {
        java.lang.Object ref = sourceType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *&#47; Source of the message. For Cloud Foundry, this can be "APP", "RTR", "DEA", "STG", etc.
       * </pre>
       *
       * <code>optional string source_type = 5;</code>
       */
      public Builder setSourceType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sourceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; Source of the message. For Cloud Foundry, this can be "APP", "RTR", "DEA", "STG", etc.
       * </pre>
       *
       * <code>optional string source_type = 5;</code>
       */
      public Builder clearSourceType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sourceType_ = getDefaultInstance().getSourceType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; Source of the message. For Cloud Foundry, this can be "APP", "RTR", "DEA", "STG", etc.
       * </pre>
       *
       * <code>optional string source_type = 5;</code>
       */
      public Builder setSourceTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sourceType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sourceInstance_ = "";
      /**
       * <pre>
       *&#47; Instance that emitted the message.
       * </pre>
       *
       * <code>optional string source_instance = 6;</code>
       */
      public boolean hasSourceInstance() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       *&#47; Instance that emitted the message.
       * </pre>
       *
       * <code>optional string source_instance = 6;</code>
       */
      public java.lang.String getSourceInstance() {
        java.lang.Object ref = sourceInstance_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sourceInstance_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *&#47; Instance that emitted the message.
       * </pre>
       *
       * <code>optional string source_instance = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSourceInstanceBytes() {
        java.lang.Object ref = sourceInstance_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceInstance_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *&#47; Instance that emitted the message.
       * </pre>
       *
       * <code>optional string source_instance = 6;</code>
       */
      public Builder setSourceInstance(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        sourceInstance_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; Instance that emitted the message.
       * </pre>
       *
       * <code>optional string source_instance = 6;</code>
       */
      public Builder clearSourceInstance() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sourceInstance_ = getDefaultInstance().getSourceInstance();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; Instance that emitted the message.
       * </pre>
       *
       * <code>optional string source_instance = 6;</code>
       */
      public Builder setSourceInstanceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        sourceInstance_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:events.LogMessage)
    }

    // @@protoc_insertion_point(class_scope:events.LogMessage)
        private static final LogFactory.LogMessage DEFAULT_INSTANCE;
    static {
            DEFAULT_INSTANCE = new LogFactory.LogMessage();
    }

        public static LogFactory.LogMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LogMessage>
        PARSER = new com.google.protobuf.AbstractParser<LogMessage>() {
      public LogMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LogMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogMessage> getParserForType() {
      return PARSER;
    }

        public LogFactory.LogMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_LogMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_events_LogMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tlog.proto\022\006events\"\305\001\n\nLogMessage\022\017\n\007me" +
      "ssage\030\001 \002(\014\0224\n\014message_type\030\002 \002(\0162\036.even" +
      "ts.LogMessage.MessageType\022\021\n\ttimestamp\030\003" +
      " \002(\003\022\016\n\006app_id\030\004 \001(\t\022\023\n\013source_type\030\005 \001(" +
      "\t\022\027\n\017source_instance\030\006 \001(\t\"\037\n\013MessageTyp" +
      "e\022\007\n\003OUT\020\001\022\007\n\003ERR\020\002B/\n!org.cloudfoundry." +
      "dropsonde.eventsB\nLogFactory"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_events_LogMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_events_LogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_events_LogMessage_descriptor,
        new java.lang.String[] { "Message", "MessageType", "Timestamp", "AppId", "SourceType", "SourceInstance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
