name: Multiapps Controller Sonar Scan

on:
  push:
   branches: [ "master" ]
  pull_request:
   branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Build and Analyze Code Coverage
      run: mvn clean install -Pcoverage
      
    - name: Sonar Scan
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar -Dsonar.projectKey=cloudfoundry_multiapps-controller

