name: Multiapps Controller Sonar Scan

on:
  push:
   branches: [ "master" ]
  pull_request:
   branches: [ "master" ]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up JDK 25
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
      with:
        java-version: '25'
        distribution: 'zulu'

    - name: Build and Analyze Code Coverage
      run: mvn clean install -Pcoverage
      
    - name: Sonar Scan
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar -Dsonar.projectKey=cloudfoundry_multiapps-controller

